apiVersion: v1
kind: Service
metadata:
  name: nsxtpanel-svc
spec:
  type: LoadBalancer
  # loadBalancerIP: 192.168.155.44
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nsxtpanel
