apiVersion: v1
kind: ConfigMap
metadata:
  name: nsxtpanel-configmap
  namespace: nsxtpanel-app
data:
  # The NSX-T config params
  nsxIPaddress: 192.168.110.26 # NSX-T Manager Hostname/IP Address
  nsxUsername: admin # The NSX-T Manager API username
  nsxtier0: bab9a262-c530-4406-ad8d-804014e2769f # The NSX-T Manager Tier-0 Router ID
  # The app config params
  pullInterval: "3" # The update intervals for the app to pull data from NSX-T Manager via APIs
  appBrand: ACME # The company name/brand showing on the top nav-bar of the app
---
apiVersion: v1
kind: Secret
metadata:
  name: nsxtpanel-secret
stringData:
  # Those passwords will be encoded with base64 on the fly when the k8s secret is created
  nsxPassword: VMware1!
  appPass: VMware1!
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsx-t-panel-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nsxtpanel
    spec:
      containers:
        - name: nsxtpanel
          image: hanymichael/single-express-react-nsxt-panel:v0.6
          ports:
            - name: nodejs-port
              containerPort: 3000
          env:
            - name: nsxIPaddress
              valueFrom:
                configMapKeyRef:
                  name: nsxtpanel-configmap
                  key: nsxIPaddress
            - name: nsxUsername
              valueFrom:
                configMapKeyRef:
                  name: nsxtpanel-configmap
                  key: nsxUsername
            - name: nsxPassword
              valueFrom:
                secretKeyRef:
                  name: nsxtpanel-secret
                  key: nsxPassword
            - name: nsxtier0
              valueFrom:
                configMapKeyRef:
                  name: nsxtpanel-configmap
                  key: nsxtier0
            - name: pullInterval
              valueFrom:
                configMapKeyRef:
                  name: nsxtpanel-configmap
                  key: pullInterval
            - name: appBrand
              valueFrom:
                configMapKeyRef:
                  name: nsxtpanel-configmap
                  key: appBrand
            - name: appPass
              valueFrom:
                secretKeyRef:
                  name: nsxtpanel-secret
                  key: appPass
---
apiVersion: v1
kind: Service
metadata:
  name: nsxtpanel-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nsxtpanel
